apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "praeco.fullname" . }}-config
  labels:
    app: {{ template "praeco.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  praeco_config: |-
    {
      "appUrl": "{{ .Values.praeco.schema }}://{{ .Values.praeco.external_host }}:{{ .Values.praeco.port }}",
      "errorLoggerUrl": "",
      "hidePreconfiguredFields": []
    }
