{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "praeco.serviceAccountName" . }}
  labels:
{{ include "praeco.labels" . | indent 4 }}
{{- end -}}
